[tool.poetry]
name = "django-rest-live"
version = "1.0.4"
description = "Subscriptions for Django REST Framework over Websockets."
authors = ["Penn Labs <contact@pennlabs.org>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/caiofariavert/django-rest-live"
repository = "https://github.com/caiofariavert/django-rest-live"
documentation = "https://django-rest-live.readthedocs.io/en/latest/"
classifiers = [
    "Framework :: Django",
]
include = ["CHANGELOG.md", "LICENSE"]
exclude = ["tox.ini"]
packages = [
    { include = "rest_live" },
]

[tool.poetry.dependencies]
python = ">=3.13"
Django = ">=5.2.12"
channels = ">=4.3.2, <5.0.0"
djangorestframework = ">=3.15.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
